var Aubio = function(Aubio) {
  Aubio = Aubio || {};

var c;c||(c=typeof Aubio !== 'undefined' ? Aubio : {});var l={},q;for(q in c)c.hasOwnProperty(q)&&(l[q]=c[q]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var r=!1,t=!1,u=!1,v=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)r=!0;else if("WORKER"===c.ENVIRONMENT)t=!0;else if("NODE"===c.ENVIRONMENT)u=!0;else if("SHELL"===c.ENVIRONMENT)v=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else r="object"===typeof window,t="function"===typeof importScripts,u="object"===typeof process&&"function"===typeof require&&!r&&!t,v=!r&&!u&&!t;
if(u){var w,x;c.read=function(a,b){w||(w=require("fs"));x||(x=require("path"));a=x.normalize(a);a=w.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});process.on("unhandledRejection",function(){process.exit(1)});c.inspect=function(){return"[Emscripten Module object]"}}else if(v)"undefined"!=
typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(r||t)c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(c.readBinary=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};else throw Error("not compiled for this environment");
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(q in l)l.hasOwnProperty(q)&&(c[q]=l[q]);l=void 0;function aa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ba={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},z=0;function assert(a,b){a||A("Assertion failed: "+b)}
var ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function B(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,C,D,E,da,F,G,ea,fa;
function ha(){c.HEAP8=C=new Int8Array(buffer);c.HEAP16=E=new Int16Array(buffer);c.HEAP32=F=new Int32Array(buffer);c.HEAPU8=D=new Uint8Array(buffer);c.HEAPU16=da=new Uint16Array(buffer);c.HEAPU32=G=new Uint32Array(buffer);c.HEAPF32=ea=new Float32Array(buffer);c.HEAPF64=fa=new Float64Array(buffer)}var H,I,ia,ja,J,ka,la,K;H=I=ja=J=ka=la=K=0;ia=!1;
c.reallocBuffer||(c.reallocBuffer=function(a){try{if(ArrayBuffer.v)var b=ArrayBuffer.v(buffer,a);else{var d=C;b=new ArrayBuffer(a);(new Int8Array(b)).set(d)}}catch(e){return!1}return ma(b)?b:!1});var na;try{na=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),na(new ArrayBuffer(4))}catch(a){na=function(b){return b.byteLength}}var oa=c.TOTAL_STACK||5242880,L=c.TOTAL_MEMORY||16777216;
L<oa&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+L+"! (TOTAL_STACK="+oa+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:L/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(L),c.buffer=buffer);ha();F[0]=1668509029;E[1]=25459;if(115!==D[2]||99!==D[3])throw"Runtime error: expected the system to be little-endian!";
function M(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.l;"number"===typeof d?void 0===b.b?c.dynCall_v(d):c.dynCall_vi(d,b.b):d(void 0===b.b?null:b.b)}}}var pa=[],qa=[],ra=[],sa=[],ta=[],ua=!1;function va(){var a=c.preRun.shift();pa.unshift(a)}var N=0,wa=null,O=null;c.preloadedImages={};c.preloadedAudios={};function P(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(p){A(p)}}function b(){return c.wasmBinary||!r&&!t||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){k=a.exports;if(k.memory){a=k.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;ha()}c.asm=k;c.usingWasm=!0;N--;c.monitorRunDependencies&&c.monitorRunDependencies(N);0==N&&(null!==wa&&(clearInterval(wa),wa=null),O&&(a=O,O=null,a()))}
function e(a){d(a.instance)}function p(a){b().then(function(a){return WebAssembly.instantiate(a,g)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);A(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=a;N++;c.monitorRunDependencies&&c.monitorRunDependencies(N);
if(c.instantiateWasm)try{return c.instantiateWasm(g,d)}catch(La){return c.printErr("Module.instantiateWasm callback failed with error: "+La),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||P(f)||"function"!==typeof fetch?p(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),g).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");p(e)});return{}}var e="aubio.wast",f="aubio.wasm",
h="aubio.temp.asm.js";"function"===typeof c.locateFile&&(P(e)||(e=c.locateFile(e)),P(f)||(f=c.locateFile(f)),P(h)||(h=c.locateFile(h)));var g={global:null,env:null,asm2wasm:ba,parent:c},k=null;c.asmPreload=c.asm;var m=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===n)var b=m(a);else a:{a=B(a,c.usingWasm?65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(Ua){b=null;break a}b=void 0}return b};var n=
"";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);b.tableBase||(b.tableBase=0);b=d(b);assert(b,"no binaryen method succeeded.");return b}})();H=1024;I=H+9808;qa.push({l:function(){xa()}});
c.STATIC_BASE=H;c.STATIC_BUMP=9808;I+=16;var Q=0;function R(){Q+=4;return F[Q-4>>2]}var ya={};
function T(a,b){Q=b;try{var d=R(),e=R(),f=R();a=0;T.f||(T.f=[null,[],[]],T.j=function(a,b){var d=T.f[a];assert(d);if(0===b||10===b){a=1===a?c.print:c.printErr;a:{for(var e=b=0;d[e];)++e;if(16<e-b&&d.subarray&&ca)b=ca.decode(d.subarray(b,e));else for(e="";;){var f=d[b++];if(!f){b=e;break a}if(f&128){var g=d[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=d[b++]&63;if(224==(f&240))f=(f&15)<<12|g<<6|h;else{var k=d[b++]&63;if(240==(f&248))f=(f&7)<<18|g<<12|h<<6|k;else{var m=d[b++]&
63;if(248==(f&252))f=(f&3)<<24|g<<18|h<<12|k<<6|m;else{var n=d[b++]&63;f=(f&1)<<30|g<<24|h<<18|k<<12|m<<6|n}}}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}}a(b);d.length=0}else d.push(b)});for(b=0;b<f;b++){for(var h=F[e+8*b>>2],g=F[e+(8*b+4)>>2],k=0;k<g;k++)T.j(d,D[h+k]);a+=g}return a}catch(m){return"undefined"!==typeof FS&&m instanceof FS.c||A(m),-m.g}}
function za(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Aa=void 0;function U(a){for(var b="";D[a];)b+=Aa[D[a++]];return b}var Ba={},Ca={},Da={};function Ea(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var d=a.charCodeAt(0);a=48<=d&&57>=d?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Fa(a){var b=Error,d=Ea(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(b.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}var Ga=void 0;function V(a){throw new Ga(a);}
function W(a,b,d){d=d||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||V('type "'+e+'" must have a positive integer typeid pointer');if(Ca.hasOwnProperty(a)){if(d.s)return;V("Cannot register type '"+e+"' twice")}Ca[a]=b;delete Da[a];Ba.hasOwnProperty(a)&&(b=Ba[a],delete Ba[a],b.forEach(function(a){a()}))}var Ha=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ia(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ha.length?Ha.pop():X.length;X[b]={u:1,value:a};return b}}function Ja(a){return this.fromWireType(G[a>>2])}function Ka(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ma(a,b){switch(b){case 2:return function(a){return this.fromWireType(ea[a>>2])};case 3:return function(a){return this.fromWireType(fa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Na(a,b,d){switch(b){case 0:return d?function(a){return C[a]}:function(a){return D[a]};case 1:return d?function(a){return E[a>>1]}:function(a){return da[a>>1]};case 2:return d?function(a){return F[a>>2]}:function(a){return G[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Oa=Array(256),Y=0;256>Y;++Y)Oa[Y]=String.fromCharCode(Y);Aa=Oa;Ga=c.BindingError=Fa("BindingError");c.InternalError=Fa("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};assert(!ia);var Pa=I;I=I+4+15&-16;K=Pa;ja=J=aa(I);ka=ja+oa;la=aa(ka);F[K>>2]=la;ia=!0;c.wasmTableSize=66;c.wasmMaxTableSize=66;c.h={};
c.i={abort:A,enlargeMemory:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(F[K>>2]>b)return!1;var d=L;for(L=Math.max(L,16777216);L<F[K>>2];)536870912>=L?L=B(2*L,a):L=Math.min(B((3*L+2147483648)/4,a),b);a=c.reallocBuffer(L);if(!a||a.byteLength!=L)return L=d,!1;c.buffer=buffer=a;ha();return!0},getTotalMemory:function(){return L},abortOnCannotGrowMemory:function(){A("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+L+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___setErrNo:function(a){c.___errno_location&&(F[c.___errno_location()>>2]=a);return a},___syscall140:function(a,b){Q=b;try{var d=ya.m();R();var e=R(),f=R(),h=R();FS.A(d,e,h);F[f>>2]=d.position;d.o&&0===e&&0===h&&(d.o=null);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.c||A(g),-g.g}},___syscall146:T,___syscall54:function(a,b){Q=b;return 0},___syscall6:function(a,b){Q=b;try{var d=ya.m();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.c||A(e),-e.g}},__embind_register_bool:function(a,
b,d,e,f){var h=za(d);b=U(b);W(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===d)var e=C;else if(2===d)e=E;else if(4===d)e=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>h])},a:null})},__embind_register_emval:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(a){var b=X[a].value;4<a&&0===--X[a].u&&(X[a]=void 0,Ha.push(a));return b},toWireType:function(a,b){return Ia(b)},
argPackAdvance:8,readValueFromPointer:Ja,a:null})},__embind_register_float:function(a,b,d){d=za(d);b=U(b);W(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ka(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Ma(b,d),a:null})},__embind_register_integer:function(a,b,d,e,f){function h(a){return a}b=U(b);-1===f&&(f=4294967295);var g=za(d);if(0===e){var k=32-8*d;h=function(a){return a<<
k>>>k}}var m=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:h,toWireType:function(a,d){if("number"!==typeof d&&"boolean"!==typeof d)throw new TypeError('Cannot convert "'+Ka(d)+'" to '+this.name);if(d<e||d>f)throw new TypeError('Passing a number "'+Ka(d)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return m?d>>>0:d|0},argPackAdvance:8,readValueFromPointer:Na(b,g,0!==e),a:null})},__embind_register_memory_view:function(a,b,d){function e(a){a>>=
2;var b=G;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=U(d);W(a,{name:d,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{s:!0})},__embind_register_std_string:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(a){for(var b=G[a>>2],d=Array(b),h=0;h<b;++h)d[h]=String.fromCharCode(D[a+4+h]);Z(a);return d.join("")},toWireType:function(a,b){function d(a,b){return a[b]}function e(a,b){return a.charCodeAt(b)}
b instanceof ArrayBuffer&&(b=new Uint8Array(b));var g;b instanceof Uint8Array?g=d:b instanceof Uint8ClampedArray?g=d:b instanceof Int8Array?g=d:"string"===typeof b?g=e:V("Cannot pass non-string to std::string");var k=b.length,m=Qa(4+k);G[m>>2]=k;for(var n=0;n<k;++n){var p=g(b,n);255<p&&(Z(m),V("String has UTF-16 code units that do not fit in 8 bits"));D[m+4+n]=p}null!==a&&a.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:Ja,a:function(a){Z(a)}})},__embind_register_std_wstring:function(a,
b,d){d=U(d);if(2===b){var e=function(){return da};var f=1}else 4===b&&(e=function(){return G},f=2);W(a,{name:d,fromWireType:function(a){for(var b=e(),d=G[a>>2],h=Array(d),n=a+4>>f,p=0;p<d;++p)h[p]=String.fromCharCode(b[n+p]);Z(a);return h.join("")},toWireType:function(a,d){var h=e(),g=d.length,n=Qa(4+g*b);G[n>>2]=g;for(var p=n+4>>f,S=0;S<g;++S)h[p+S]=d.charCodeAt(S);null!==a&&a.push(Z,n);return n},argPackAdvance:8,readValueFromPointer:Ja,a:function(a){Z(a)}})},__embind_register_void:function(a,b){b=
U(b);W(a,{w:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_emscripten_memcpy_big:function(a,b,d){D.set(D.subarray(b,b+d),a);return a},_llvm_log10_f32:function(a){return Math.log(a)/Math.LN10},DYNAMICTOP_PTR:K,STACKTOP:J};var Ra=c.asm(c.h,c.i,buffer);c.asm=Ra;var xa=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)};c.___getTypeName=function(){return c.asm.___getTypeName.apply(null,arguments)};
c._destroyBuffer=function(){return c.asm._destroyBuffer.apply(null,arguments)};c._dispose=function(){return c.asm._dispose.apply(null,arguments)};var ma=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Z=c._free=function(){return c.asm._free.apply(null,arguments)};c._getOnset=function(){return c.asm._getOnset.apply(null,arguments)};c._getTempo=function(){return c.asm._getTempo.apply(null,arguments)};
c._initTempo=function(){return c.asm._initTempo.apply(null,arguments)};var Qa=c._malloc=function(){return c.asm._malloc.apply(null,arguments)};c._newBuffer=function(){return c.asm._newBuffer.apply(null,arguments)};c._processTempo=function(){return c.asm._processTempo.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.asm=Ra;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};
function y(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}y.prototype=Error();y.prototype.constructor=y;O=function Sa(){c.calledRun||Ta();c.calledRun||(O=Sa)};
function Ta(){function a(){if(!c.calledRun&&(c.calledRun=!0,!z)){ua||(ua=!0,M(qa));M(ra);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();ta.unshift(a)}M(ta)}}if(!(0<N)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)va();M(pa);0<N||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=Ta;c.exit=function(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(z=!0,J=void 0,M(sa),c.onExit))c.onExit(a);u&&process.exit(a);c.quit(a,new y(a))}};function A(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=A;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;Ta();


  return Aubio;
};
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Aubio;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Aubio; });
  else if (typeof exports === 'object')
    exports["Aubio"] = Aubio;
  